{% set name = "singularity-compose" %}
{% set version = "0.0.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18104be8b87958338fd80138d8313d5312632182a8f73e1ed3252b2643cbda02

build:
  number: 0
  noarch: python
  entry_points:
    - singularity-compose=scompose.client:start
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - python >=3
    - requests
    - pyaml
    - spython >=0.0.67

test:
  imports:
    - scompose
    - scompose.client
    - scompose.client.build
    - scompose.client.config
    - scompose.client.create
    - scompose.client.down
    - scompose.client.exec
    - scompose.client.logs
    - scompose.client.ps
    - scompose.client.restart
    - scompose.client.shell
    - scompose.client.up
    - scompose.logger
    - scompose.project
    - scompose.project.project
    - scompose.project.instance
    - scompose.tests
    - scompose.utils
  commands:
    - singularity-compose --help
  requires:
    - pytest

about:
  home: http://www.github.com/singularityhub/singularity-compose
  license: AGPL-3.0
  license_family: OTHER
  license_file: LICENSE
  summary: Simple orchestration for Singularity container instances
  doc_url: https://singularityhub.github.io/singularity-compose
  dev_url: https://www.github.com/singularityhub/singularity-compose

extra:
  recipe-maintainers:
    - vsoch
