travis:
  secure:
    BINSTAR_TOKEN: EeEGB1Ys6eGDXW3lFR1SRMB4DO0M8uk6Rb6BxNmTyYWQ95ahkcEO4tDEuZ/tn5t/2gSb80G2qq1KZ0WgB18Lgw0KwtDTmIMoufHft1ELDTNpuXoLi34Q7ZAeHToqtyqXL9Lp+/sLiW3n3xAqKI0vkNAB+ur+1enlaU+H/Lp57ifXMvlxdluoFf0g5JB7vNYhnBnrcVrmLGLqegoLmWvhPEeSTGccJQGDKDpcgHi4BDbWovdEUkpku8ga7690DshRmx8hn7DHU/1wUqmmj2KWmB7Ed3vI6Jhz40oC5V2TWziBslCw64fxStKR1n6QoJCQnNDPWIy28KPwZlSfrXSth3ObYoF3mLWxrQhYuPdsiuO60iOoI5mfrGjHTW+sTqmltxpi1EJrel23d8ZgGDAZuuouUtny/gYENwhffFuWl0YQ4S34xyoQRgCX9VPEEuoVqsbHZZTGiTNKrHkphzr9f/1c+RQvw4nfVEaFVskdsnHmPFLccM5L/s2QOU1xLrGLKuciLIm4lbFxz+NdUoxYvRdpv/LcI3YCs6Vo6maREPfVhc5ZdyKLKwiOMQOaDL07kaE7y/86ei/rhWnKw3suf5pMDy9wR6Uaf8CLTnVTZHTBtvfappkp75UBqVYlnEW+NgHX1JVE/horqQCCJJBC2AOGJgY26xkYcusoZxnsY1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
